Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans. NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides efficient data structures, functions, and tools that enhance Python’s capabilities for handling large datasets, performing numerical operations, and conducting scientific computations.

Advantages of NumPy

1. Efficient Multi-Dimensional Arrays (ndarray)

    NumPy introduces the ndarray object, which is a fast and memory-efficient alternative to Python lists.

    Supports multi-dimensional arrays with advanced indexing and slicing capabilities.

2. Performance Optimization

    NumPy operations are implemented in C and Fortran, making them significantly faster than equivalent Python loops.

    Supports vectorized operations that eliminate the need for explicit loops.

3. Comprehensive Mathematical Functions

    Includes functions for linear algebra, statistical operations, Fourier transforms, and more.

    Offers universal functions (ufuncs) for element-wise operations.

4. Broadcasting Mechanism

    Enables operations between arrays of different shapes without creating unnecessary copies.

    Reduces memory overhead and enhances performance.

5. Memory Efficiency

    Uses a fixed type for array elements, consuming less memory compared to Python lists.

    Avoids the overhead of storing type information for each element.

6. Integration with Other Libraries

    Works seamlessly with libraries like SciPy, Pandas, Matplotlib, TensorFlow, and Scikit-learn.

    Provides a foundation for data analysis and machine learning applications.

7. Support for Large Datasets

    Designed to handle large numerical datasets efficiently.

    Optimized for high-performance computing tasks.

Enhancing Python’s Capabilities for Numerical Operations

    Vectorization: NumPy allows performing operations on entire arrays without writing explicit loops, making computations faster and more readable.

    Better Indexing & Slicing: Supports advanced slicing, boolean masking, and fancy indexing for flexible data manipulation.

    Parallelism & Multithreading: Uses optimized BLAS and LAPACK implementations for parallel computations.

    Interfacing with Other Languages: Can interact with C, C++, and Fortran for performance-critical tasks.

Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans. Comparison of np.mean() and np.average() in NumPy
Both np.mean() and np.average() compute the average value of an array, but they have key differences in how they handle weights and their functionality.

Key Differences

1. Weighted Average Capability

    np.mean() only calculates the simple arithmetic mean.
    
    np.average() allows specifying weights, making it useful when some values contribute more than others.

2. Output Differences with Weights

    If weights are not provided, np.average() behaves like np.mean().

    If weights are provided, np.average() calculates the weighted mean:


Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Ans. Methods for Reversing a NumPy Array Along Different Axes
NumPy provides multiple ways to reverse an array, either fully or along specific dimensions (axes).

1. Reversing a 1D Array

    For a one-dimensional (1D) array, we can reverse the elements using slicing or built-in functions.

Method 1: Using Slicing ([::-1])

In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]

print(reversed_1d)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


Method 2: Using np.flip()

In [2]:
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


2. Reversing a 2D Array (Along Different Axes)

    Original 2D Array

In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Method 1: Reverse Entire 2D Array ([::-1, ::-1])

    Reverses both rows and columns.

In [5]:
reversed_2d = arr_2d[::-1, ::-1]
print(reversed_2d)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Method 2: Using np.flip()

(a) Reverse Along Rows (axis=0)

In [6]:
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


(b) Reverse Along Columns (axis=1)

In [7]:
reversed_columns = np.flip(arr_2d, axis=1)
print(reversed_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans. Determining the Data Type of Elements in a NumPy Array
NumPy provides attributes and functions to determine the data type (dtype) of elements in an array.

Method 1: Using .dtype Attribute

The .dtype attribute returns the data type of elements in the array.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int32 or int64 (depends on system)

int64


Method 2: Using np.result_type()

This function determines the common data type of given inputs.

In [9]:
dtype = np.result_type(3, 4.5, np.array([1, 2, 3]))
print(dtype)  # Output: float64

float64


Method 3: Using np.can_cast()

Checks if a NumPy array can be safely cast to another data type.

In [10]:
print(np.can_cast(arr.dtype, np.float64))  # Output: True

True


Importance of Data Types in Memory Management and Performance

1. Memory Efficiency

    Different data types consume different amounts of memory.

    Example: int32 takes 4 bytes per element, while int64 takes 8 bytes.

    Choosing an optimal data type can significantly reduce memory usage for large datasets.

2. Computational Performance

    Smaller data types allow faster computations because they require fewer CPU cycles.

    Example: float32 operations are faster than float64 on most systems.

3. Avoiding Type Conversion Overhead

    Operations on arrays with different data types may cause implicit type conversions, which slow down computations.

    Example:

In [11]:
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
result = arr1 + arr2  # Implicit conversion to float64
print(result.dtype)  # Output: float64

float64


4. Precision Control

    Floating-point calculations are prone to precision errors.

    Example: float32 may lose precision in large numerical computations, whereas float64 is more accurate.

5. Compatibility with External Systems

    Data type selection is crucial when interfacing with databases, machine learning frameworks (e.g., TensorFlow), or hardware-specific optimizations.


Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. Definition of ndarrays in NumPy

    An ndarray (n-dimensional array) is the fundamental data structure in NumPy, used for storing large, multi-dimensional homogeneous data. It is an efficient, flexible, and optimized array-like structure that supports mathematical operations and complex computations.

Key Features of ndarrays

1. Homogeneous Data: All elements in an ndarray must be of the same data type (e.g., integers, floats, or complex numbers).

2. Fixed Size: Once created, the size of an ndarray cannot be changed (unlike Python lists).

3. Efficient Memory Storage: Stores elements in contiguous memory blocks, which improves speed and reduces overhead.

4. Vectorized Operations: Supports element-wise arithmetic operations and broadcasting, reducing the need for explicit loops.

5. Multidimensional Support: Can have any number of dimensions (ndim), making it suitable for complex mathematical operations.

6. Indexing & Slicing: Provides advanced slicing techniques, including boolean and fancy indexing.

7. Integrated with Mathematical Functions: Works seamlessly with NumPy's built-in mathematical functions (e.g., np.sum(), np.mean()).

Differences Between ndarrays and Python Lists

1. Data Type
    Numpy Ndarrays: Homogeneous
    
    Python lists: Heterogeneous
2. Memory Efficiency
    Numpy Ndarrays:More efficient (contiguous memory)

    Python lists:Less efficient (pointers to objects)
3. Performance
    Numpy Ndarrays: Faster (vectorized operations, optimized C implementation)

    Python lists: Slower (requires Python loops for operations)
4. Dimensionality
    Numpy Ndarrays:  Supports multi-dimensional arrays

    Python lists: Only 1D natively (nested lists for higher dimensions)
5. Operations
    Numpy Ndarrays: Supports element-wise operations & broadcasting

    Python lists: Requires loops or list comprehensions
6. Indexing
    Numpy Ndarrays: Advanced (boolean, fancy indexing)

    Python lists: Basic (single/multi-level indexing)


Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. Performance Benefits of NumPy Arrays Over Python Lists

When working with large-scale numerical operations, NumPy arrays (ndarray) significantly outperform Python lists due to several key optimizations. Below are the main advantages and their impact on performance:

1. Memory Efficiency
    NumPy arrays store elements in a contiguous block of memory, making them more compact and reducing memory overhead.

    Python lists store references to objects, increasing memory usage, especially for large datasets.

 Example: Checking memory usage

In [12]:
import numpy as np
import sys

size = 1_000_000

# NumPy array
arr = np.arange(size)
print("NumPy array size (bytes):", arr.nbytes)

# Python list
lst = list(range(size))
print("Python list size (bytes):", sys.getsizeof(lst) + sum(sys.getsizeof(i) for i in lst))


NumPy array size (bytes): 8000000
Python list size (bytes): 36000056


2. Computational Speed (Vectorization & Broadcasting)

    NumPy leverages optimized C and Fortran libraries to execute operations in compiled code.

    Python lists require explicit loops, making them much slower for mathematical computations.

Example: Element-wise addition

In [13]:
import time

size = 1_000_000

# NumPy array addition
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2  # Vectorized operation
print("NumPy execution time:", time.time() - start)

# Python list addition
lst1 = list(range(size))
lst2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(lst1, lst2)]  # Using list comprehension
print("Python list execution time:", time.time() - start)


NumPy execution time: 0.01756453514099121
Python list execution time: 0.10935735702514648


3. Avoidance of Loop Overhead

    NumPy operations are performed in compiled C code, while Python loops introduce interpretation overhead.

    This is especially beneficial for large-scale computations.

Example: Squaring elements

In [14]:
size = 1_000_000
arr = np.arange(size)

# NumPy vectorized squaring
start = time.time()
arr **= 2  # Element-wise operation
print("NumPy execution time:", time.time() - start)

# Python loop squaring
lst = list(range(size))
start = time.time()
lst = [x**2 for x in lst]
print("Python list execution time:", time.time() - start)


NumPy execution time: 0.0017709732055664062
Python list execution time: 0.1100163459777832


4. Built-in Mathematical & Statistical Functions

    NumPy provides optimized mathematical functions like np.sum(), np.mean(), and np.dot(), which are significantly faster than their Python equivalents.

Example: Summing elements

In [15]:
size = 1_000_000
arr = np.arange(size)
lst = list(range(size))

# NumPy sum
start = time.time()
np.sum(arr)
print("NumPy sum execution time:", time.time() - start)

# Python sum
start = time.time()
sum(lst)
print("Python list sum execution time:", time.time() - start)


NumPy sum execution time: 0.0014998912811279297
Python list sum execution time: 0.00836324691772461


5. Support for Parallel Processing

    NumPy operations use SIMD (Single Instruction, Multiple Data) and parallel processing under the hood.

    Python lists execute operations sequentially, making them slower.

Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Ans. Comparison of vstack() and hstack() in NumPy

  Both vstack() and hstack() are used for stacking (combining) arrays, but they work in different ways:
1. numpy.vstack() - Vertical Stacking

    Stacks arrays vertically (row-wise), increasing the number of rows.

    Input arrays must have the same number of columns.

Example: Using vstack()

In [16]:
import numpy as np

a = np.array([[1, 2], [3, 4]])  # 2x2 array
b = np.array([[5, 6]])          # 1x2 array

result = np.vstack((a, b))  # Stack along rows
print(result)

[[1 2]
 [3 4]
 [5 6]]


2. numpy.hstack() - Horizontal Stacking

    Stacks arrays horizontally (column-wise), increasing the number of columns.

    Input arrays must have the same number of rows.

Example: Using hstack()

In [17]:
c = np.array([[1, 2], [3, 4]])  # 2x2 array
d = np.array([[5], [6]])        # 2x1 array

result = np.hstack((c, d))  # Stack along columns
print(result)

[[1 2 5]
 [3 4 6]]


Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Ans. Differences Between fliplr() and flipud() in NumPy

Both fliplr() and flipud() are used to flip arrays along different axes, but they serve different purposes:

1. numpy.fliplr() – Flip Left to Right (Horizontally)

    Works on 2D or higher arrays.

    Reverses the order of columns, but rows remain unchanged.

Example: Using fliplr()

In [18]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped_lr = np.fliplr(arr)
print(flipped_lr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. numpy.flipud() – Flip Upside Down (Vertically)

    Works on 2D or higher arrays.

    Reverses the order of rows, but columns remain unchanged.

Example: Using flipud()

In [19]:
flipped_ud = np.flipud(arr)
print(flipped_ud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Effects on Higher-Dimensional Arrays

    Both functions only affect the first two dimensions of an array.

    For 3D arrays, they flip each 2D slice independently.

Example: 3D Array Flip

In [20]:
arr_3d = np.arange(1, 13).reshape(2, 3, 2)
print("Original Array:\n", arr_3d)

print("\nFliplr:\n", np.fliplr(arr_3d))
print("\nFlipud:\n", np.flipud(arr_3d))


Original Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Fliplr:
 [[[ 5  6]
  [ 3  4]
  [ 1  2]]

 [[11 12]
  [ 9 10]
  [ 7  8]]]

Flipud:
 [[[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]]]


Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. Understanding numpy.array_split() Method

The numpy.array_split() method is used to split an array into multiple sub-arrays along a specified axis. Unlike np.split(), which requires an even division, np.array_split() handles uneven splits gracefully by creating smaller sub-arrays as needed.

Syntax:

    arr: The input NumPy array.

    sections: The number of parts to split the array into.

    axis: The axis along which to split (default is axis=0, i.e., row-wise for 2D arrays).

Handling Uneven Splits

    If the array cannot be divided equally, array_split() distributes extra elements into the first few sub-arrays.

    This means that the first few sub-arrays will have an extra element compared to the rest.

Example 1: Even Split

Splitting a 1D array evenly

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.array_split(arr, 3)  # Splitting into 3 equal parts

for i, sub in enumerate(split_arrays):
    print(f"Sub-array {i+1}: {sub}")

Sub-array 1: [1 2]
Sub-array 2: [3 4]
Sub-array 3: [5 6]


Example 2: Uneven Split

Splitting a 1D array unevenly

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arrays = np.array_split(arr, 3)  # Splitting into 3 parts (unevenly)

for i, sub in enumerate(split_arrays):
    print(f"Sub-array {i+1}: {sub}")

Sub-array 1: [1 2 3]
Sub-array 2: [4 5]
Sub-array 3: [6 7]


Example 3: Splitting a 2D Array

Splitting a 2D array along rows (axis=0)

In [24]:
arr2D = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
split_2D = np.array_split(arr2D, 3, axis=0)  # Splitting into 3 parts row-wise

for i, sub in enumerate(split_2D):
    print(f"Sub-array {i+1}:\n{sub}\n")

Sub-array 1:
[[1 2]
 [3 4]]

Sub-array 2:
[[5 6]]

Sub-array 3:
[[7 8]]



Example 4: Splitting Along Columns (axis=1)

Column-wise splitting

In [25]:
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
split_col = np.array_split(arr2D, 3, axis=1)  # Split into 3 parts column-wise

for i, sub in enumerate(split_col):
    print(f"Sub-array {i+1}:\n{sub}\n")

Sub-array 1:
[[1 2]
 [5 6]]

Sub-array 2:
[[3]
 [7]]

Sub-array 3:
[[4]
 [8]]



Q10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans. Vectorization and Broadcasting in NumPy

NumPy is optimized for high-performance numerical computing, and two of its most powerful features—vectorization and broadcasting—enable fast and efficient array operations by avoiding slow Python loops.

1. Vectorization

    Vectorization refers to the process of performing operations on entire arrays instead of using explicit Python loops. NumPy achieves this using highly optimized C and Fortran libraries, allowing computations to be performed in a single operation.

Benefits of Vectorization

    Faster Execution: Operations are executed at compiled speeds rather than interpreted Python loop speeds.
    
    Cleaner Code: Eliminates the need for manual looping, making the code more readable.

    Memory Efficiency: Reduces overhead by leveraging contiguous memory storage.

Example: Squaring Elements Using Vectorization vs. Loop

Using a Python Loop (Slow)

In [26]:
import numpy as np
import time

size = 1_000_000
arr = np.arange(size)

# Using a loop
start = time.time()
result = [x**2 for x in arr]
print("Loop Execution Time:", time.time() - start)

Loop Execution Time: 0.1286475658416748


Using NumPy Vectorization (Fast)

In [27]:
# Using NumPy vectorized operation
start = time.time()
result = arr ** 2  # Element-wise squaring
print("NumPy Vectorized Execution Time:", time.time() - start)

NumPy Vectorized Execution Time: 0.0035047531127929688


    Vectorization is significantly faster than using loops since NumPy leverages compiled low-level operations.

2. Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes without explicit looping or reshaping. It expands smaller arrays to match the shape of larger ones without actually copying data, making operations memory-efficient and fast.

Rules of Broadcasting

When performing operations between arrays of different shapes, NumPy follows these rules:

1. Compare dimensions from right to left.

2. If dimensions are equal, they remain unchanged.

3. If one of the dimensions is 1, it is broadcasted (expanded) to match the other dimension.

4. If dimensions mismatch and neither is 1, NumPy raises an error.

Example 1: Broadcasting in a Simple Operation

In [28]:
arr1 = np.array([1, 2, 3])   # Shape: (3,)
arr2 = np.array([[10],       # Shape: (3,1)
                 [20],
                 [30]])

result = arr1 + arr2  # Broadcasting occurs
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


Example 2: Broadcasting in 2D Arrays

Adding a 1D array to a 2D array

In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2,3)
arr2 = np.array([10, 20, 30])            # Shape: (3,)

result = arr1 + arr2  # Broadcasting occurs
print(result)

[[11 22 33]
 [14 25 36]]


# Practical Questions

Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

Ans.

In [30]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

# Step 2: Interchange rows and columns (Transpose)
transposed_arr = arr.T
print("\nTransposed Array:\n", transposed_arr)

Original Array:
 [[80  7 82]
 [50 60 25]
 [72 13 66]]

Transposed Array:
 [[80 50 72]
 [ 7 60 13]
 [82 25 66]]


Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Ans.

In [31]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)  # Creates an array [1, 2, ..., 10]
print("1D Array:\n", arr)

# Step 2: Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5:\n", arr_2x5)

# Step 3: Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped to 5x2:\n", arr_5x2)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Q3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans.

In [32]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
arr = np.random.rand(4, 4)  # Generates random floats between 0 and 1
print("Original 4x4 Array:\n", arr)

# Step 2: Add a border of zeros to make it a 6x6 array
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", arr_with_border)

Original 4x4 Array:
 [[0.70877688 0.27379375 0.9874326  0.64159639]
 [0.95134821 0.60918708 0.97127197 0.387164  ]
 [0.85871892 0.17715705 0.95084389 0.60229879]
 [0.20572619 0.7140045  0.42476353 0.78046921]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.70877688 0.27379375 0.9874326  0.64159639 0.        ]
 [0.         0.95134821 0.60918708 0.97127197 0.387164   0.        ]
 [0.         0.85871892 0.17715705 0.95084389 0.60229879 0.        ]
 [0.         0.20572619 0.7140045  0.42476353 0.78046921 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Ans.

In [33]:
import numpy as np

# Create an array from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print("NumPy Array:", arr)

NumPy Array: [10 15 20 25 30 35 40 45 50 55 60]


Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

Ans.

In [34]:
import numpy as np

# Step 1: Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
upper_case = np.char.upper(arr)   # Convert to uppercase
lower_case = np.char.lower(arr)   # Convert to lowercase
title_case = np.char.title(arr)   # Convert to title case
capitalize_case = np.char.capitalize(arr)  # Capitalize first letter

# Step 3: Print results
print("Original Array:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalize:", capitalize_case)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


Ans.

In [35]:
import numpy as np

# Step 1: Create a NumPy array of words
words = np.array(['hello', 'numpy', 'python'])

# Step 2: Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Step 3: Print results
print("Original Array:", words)
print("Spaced Words:", spaced_words)

Original Array: ['hello' 'numpy' 'python']
Spaced Words: ['h e l l o' 'n u m p y' 'p y t h o n']


Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Ans.

In [36]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
A = np.array([[2, 4, 6], [8, 10, 12]])
B = np.array([[1, 2, 3], [4, 5, 6]])

# Step 2: Perform element-wise operations
addition = A + B        # Element-wise addition
subtraction = A - B     # Element-wise subtraction
multiplication = A * B  # Element-wise multiplication
division = A / B        # Element-wise division

# Step 3: Print results
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)

Array A:
 [[ 2  4  6]
 [ 8 10 12]]

Array B:
 [[1 2 3]
 [4 5 6]]

Element-wise Addition:
 [[ 3  6  9]
 [12 15 18]]

Element-wise Subtraction:
 [[1 2 3]
 [4 5 6]]

Element-wise Multiplication:
 [[ 2  8 18]
 [32 50 72]]

Element-wise Division:
 [[2. 2. 2.]
 [2. 2. 2.]]


Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Ans.

In [37]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


Ans.

In [38]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 1: Generate an array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)

# Step 2: Find all prime numbers in the array
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]

# Step 3: Display results
print("Original Array:\n", random_array)
print("\nPrime Numbers:\n", prime_numbers)

Original Array:
 [ 323  660  938  988  312  343  334   50  147  379  995  266  332  102
  534   86  625  510  964  665  367  610  227  827  322  748  336  286
  461  546  107  488  756  637  985  611  826  424   44  219  863  405
  855  625  281  183   11  468  126  539  145  805  254  670  930  358
 1000  242  550  716  840  819  683  141  283  682  506  804  731   96
  773  335   82  814  669  767  631   74  756  817  678  672  499  705
  354  324  916  248  658  899   65  762   34   91  549  619  106  255
  712  170]

Prime Numbers:
 [379 367 227 827 461 107 863 281  11 683 283 773 631 499 619]


Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

Ans.

In [39]:
import numpy as np

# Step 1: Generate random daily temperatures for a month (30 days)
np.random.seed(42)  # For reproducibility
daily_temperatures = np.random.uniform(15, 35, 30)  # Random temperatures between 15°C and 35°C
print("Daily Temperatures:\n", daily_temperatures)

# Step 2: Reshape into 4 weeks of 7 days each, plus 2 extra days
weeks = daily_temperatures[:28].reshape(4, 7)  # First 4 weeks (28 days)
extra_days = daily_temperatures[28:]  # Remaining 2 days

# Step 3: Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Step 4: Print weekly averages
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i}: {avg:.2f}°C")

# Step 5: Handle extra days separately if needed
if len(extra_days) > 0:
    print(f"\nAverage for last {len(extra_days)} extra days: {np.mean(extra_days):.2f}°C")

Daily Temperatures:
 [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687
 24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825]

Weekly Averages:
Week 1: 23.65°C
Week 2: 27.03°C
Week 3: 22.23°C
Week 4: 22.87°C

Average for last 2 extra days: 21.39°C
